/**
 * services/ontology/ontologyPipelineCompiler.ts
 *
 * 本体画布 (Ontology Canvas) 拓扑图到 DuckDB CTE 嵌套 SQL 管道编译器。
 * 按照 MECE 5 层拓扑依赖关系，将实体节点与连接边解析并编译为高可读性的 DuckDB SQL 代码块。
 */

export interface OntologyCteCompileInput {
  objects: Array<{
    id: number;
    name: string;
    object_type_id: number;
    properties?: string;
  }>;
  links: Array<{
    id: number;
    link_type_id: number;
    source_object_id: number;
    target_object_id: number;
    weight?: number;
  }>;
  objectTypes: Array<{
    id: number;
    name: string;
  }>;
  linkTypes: Array<{
    id: number;
    name: string;
  }>;
}

/**
 * 将本体画布的节点与拓扑连接边编译为 DuckDB CTE SQL 查询语句
 */
export function generateOntologyCtePipeline(input: OntologyCteCompileInput): string {
  const { objects, links, objectTypes, linkTypes } = input;

  if (!objects || objects.length === 0) {
    return '-- 本体画布当前无实体节点，请先在画布中添加节点';
  }

  // 1. Group objects by Object Type
  const typeMap = new Map<number, string>();
  objectTypes.forEach(t => typeMap.set(t.id, t.name.toLowerCase().replace(/[^a-z0-9_]/g, '_')));

  const linkTypeMap = new Map<number, string>();
  linkTypes.forEach(lt => linkTypeMap.set(lt.id, lt.name.toLowerCase().replace(/[^a-z0-9_]/g, '_')));

  const objectMap = new Map<number, typeof objects[0]>();
  objects.forEach(o => objectMap.set(o.id, o));

  const ctes: string[] = [];

  // 2. Build Base Objects CTE
  const baseObjectRows = objects.map(o => {
    const typeName = typeMap.get(o.object_type_id) || 'unknown';
    const safeName = o.name.replace(/'/g, "''");
    const safeProps = (o.properties || '{}').replace(/'/g, "''");
    return `  (${o.id}, '${safeName}', ${o.object_type_id}, '${typeName}', '${safeProps}')`;
  });

  ctes.push(
    `cte_base_entities AS (\n  SELECT * FROM (\n    VALUES \n${baseObjectRows.join(',\n')}\n  ) t(entity_id, entity_name, type_id, type_name, properties_json)\n)`
  );

  // 3. Build Topology Links CTE
  if (links && links.length > 0) {
    const linkRows = links.map(l => {
      const src = objectMap.get(l.source_object_id);
      const tgt = objectMap.get(l.target_object_id);
      const relName = linkTypeMap.get(l.link_type_id) || 'relates_to';
      const weight = l.weight ?? 0.5;
      const srcName = (src?.name || 'unknown').replace(/'/g, "''");
      const tgtName = (tgt?.name || 'unknown').replace(/'/g, "''");
      return `  (${l.id}, ${l.source_object_id}, '${srcName}', ${l.target_object_id}, '${tgtName}', '${relName}', ${weight})`;
    });

    ctes.push(
      `cte_semantic_relations AS (\n  SELECT * FROM (\n    VALUES \n${linkRows.join(',\n')}\n  ) t(link_id, source_id, source_name, target_id, target_name, relation_type, weight)\n)`
    );
  }

  // 4. Build Aggregated Pipeline CTE
  if (links && links.length > 0) {
    ctes.push(
      `cte_topology_pipeline AS (\n  SELECT \n    e.entity_id,\n    e.entity_name,\n    e.type_name,\n    COUNT(r.link_id) AS total_connections,\n    ROUND(AVG(COALESCE(r.weight, 0)), 2) AS avg_connection_weight,\n    LIST(r.target_name) AS linked_target_entities\n  FROM cte_base_entities e\n  LEFT JOIN cte_semantic_relations r ON e.entity_id = r.source_id\n  GROUP BY e.entity_id, e.entity_name, e.type_name\n)`
    );
  }

  // 5. Assemble final DuckDB SQL
  const sql = `-- ========================================================\n-- DuckDB Ontology Topological Pipeline Generated by AI\n-- Generated At: ${new Date().toISOString()}\n-- Entity Count: ${objects.length} | Relation Count: ${links?.length || 0}\n-- ========================================================\n\nWITH ${ctes.join(',\n\n')}\n\nSELECT * FROM ${links && links.length > 0 ? 'cte_topology_pipeline' : 'cte_base_entities'}\nORDER BY entity_id ASC;`;

  return sql;
}
