/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
        "./types.ts",
        "./App.tsx"
    ],
    darkMode: 'class',
    theme: {
        extend: {
            borderColor: {
                DEFAULT: 'var(--monokai-border)',
            },
            colors: {
                // ide.* aliases monokai CSS vars (legacy class names; prefer monokai.*)
                ide: {
                    bg: 'var(--monokai-bg)',
                    surface1: 'var(--monokai-surface)',
                    surface2: 'var(--monokai-elevated)',
                    hover: 'var(--monokai-hover)',
                    border: 'var(--monokai-border)',
                    'border-strong': 'var(--monokai-border-strong)',
                    text: 'var(--monokai-fg)',
                    muted: 'var(--monokai-fg-muted)',
                    dim: 'var(--monokai-comment)',
                    accent: 'var(--monokai-accent)',
                    success: 'var(--monokai-accent)',
                    warning: 'var(--monokai-yellow)',
                    danger: 'var(--monokai-pink)',
                },
                monokai: {
                    bg: 'var(--monokai-bg)',
                    surface: 'var(--monokai-surface)',
                    sidebar: 'var(--monokai-sidebar)',
                    elevated: 'var(--monokai-elevated)',
                    hover: 'var(--monokai-hover)',
                    border: 'var(--monokai-border)',
                    'border-subtle': 'var(--monokai-border-subtle)',
                    'border-strong': 'var(--monokai-border-strong)',
                    fg: 'var(--monokai-fg)',
                    'fg-muted': 'var(--monokai-fg-muted)',
                    'fg-dim': 'var(--monokai-comment)',
                    pink: 'var(--monokai-pink)',
                    green: 'var(--monokai-accent)',
                    yellow: 'var(--monokai-yellow)',
                    orange: 'var(--monokai-orange)',
                    blue: 'var(--monokai-cyan)',
                    cyan: 'var(--monokai-cyan)',
                    amethyst: 'var(--monokai-purple)',
                    purple: 'var(--monokai-purple)',
                    comment: 'var(--monokai-comment)',
                    accent: 'var(--monokai-accent)',
                    'accent-hover': 'var(--monokai-accent-hover)',
                    primary: 'var(--monokai-accent)',
                    success: 'var(--monokai-accent)',
                    warning: 'var(--monokai-yellow)',
                    danger: 'var(--monokai-pink)',
                    info: 'var(--monokai-cyan)',
                    red: 'var(--monokai-pink)',
                }
            },
            fontFamily: {
                mono: ['var(--font-mono)'],
                sans: ['var(--font-sans)'],
            },
            fontSize: {
                // Compact scale: body default = xs (12px)
                '3xs': ['8px',  { lineHeight: '12px' }],
                '2xs': ['10px', { lineHeight: '14px' }],
                'xs':  ['12px', { lineHeight: '16px' }],
                'sm':  ['14px', { lineHeight: '20px' }],
                'md':  ['16px', { lineHeight: '24px' }],
                'meta': ['11px', { lineHeight: '14px' }],
            },
            backgroundColor: {
                'monokai-bg': 'var(--monokai-bg)',
                'monokai-surface': 'var(--monokai-surface)',
                'monokai-sidebar': 'var(--monokai-sidebar)',
                'monokai-elevated': 'var(--monokai-elevated)',
                'monokai-hover': 'var(--monokai-hover)',
            },
            spacing: {
                'ds-1': 'var(--space-1)',
                'ds-2': 'var(--space-2)',
                'ds-3': 'var(--space-3)',
                'ds-4': 'var(--space-4)',
                'ds-5': 'var(--space-5)',
                'ds-6': 'var(--space-6)',
                'ds-8': 'var(--space-8)',
            },
            borderRadius: {
                'ds-sm': 'var(--radius-sm)',
                'ds-md': 'var(--radius-md)',
                'ds-lg': 'var(--radius-lg)',
                'ds-xl': 'var(--radius-xl)',
            },
        },
    },
    plugins: [],
}
