import React, { useState, useEffect } from 'react';
import { GenerationResult, AnalysisSummary } from '../../types';
import { duckDBService } from '../../services/duckdbService';
import { aiService } from '../../services/aiService';
import { MermaidChart } from '../../components/MermaidChart';
import { generateMermaidFromOps } from '../../utils/sqlToMermaid';
import { SchemaPreview } from './SchemaPreview';
import { QualityBadge } from './QualityBadge';
import { SchemaCard } from './SchemaCard';
import { QualityPanel } from './QualityPanel';
import { CustomAssertionPanel } from './CustomAssertionPanel';
// NEW: Enhanced UI Components
import { 
  CoreHeroCard, 
  ConfidenceBadge, 
  ConfidenceBar, 
  ReasoningToggle, 
  AssumptionBadge,
  EmptyState,
  LoadingSkeleton,
  SectionCard,
  getQualityGrade,
  getQualityColor,
  getSemanticTypeColor,
  formatNumber
} from './EnhancedUI';
import {
  ChevronDown,
  ChevronUp,
  BrainCircuit,
  Settings,
  Sparkles,
  ShieldCheck,
  Zap,
  Layout,
  BarChart3,
  Hash,
  ArrowUpRight,
  Search,
  BookOpen,
  Rocket,
  ShieldAlert,
  MousePointer2,
  Layers,
  FileCode,
  Target,
  Activity,
  MessageSquare,
  Wrench,
  Link,
  Flame,
  Clock,
  Folder,
  Download,
  Play,
  FileText,
  CheckCircle2,
  AlertTriangle,
  Database,
  Table,
  Copy,
  Terminal,
  Cpu,
  TestTube2,
  Filter,
  Ban,
  Info,
  Lightbulb
} from 'lucide-react';


interface ResultCardProps {
  result: any; // Allow for EnrichedAnalysisResult
  summary: AnalysisSummary;
  fileName: string;
  onExecuteSql: (sql: string) => void;
  onRefresh?: () => void;
  onGenerateHandbook?: () => void;
}

export const ResultCard: React.FC<ResultCardProps> = ({
  result,
  summary,
  fileName,
  onExecuteSql,
  onRefresh,
  onGenerateHandbook
}) => {
  const [selectedOperation, setSelectedOperation] = useState<number | null>(null);

  // Execution State
  const [executing, setExecuting] = useState(false);
  const [executedOps, setExecutedOps] = useState<Record<number, 'success' | 'error' | undefined>>({});

  // Preview State
  const [activePreviewId, setActivePreviewId] = useState<number | null>(null);
  const [previewData, setPreviewData] = useState<any[] | null>(null);
  const [previewError, setPreviewError] = useState<string | null>(null);

  // Chat State
  const [chatInput, setChatInput] = useState('');
  const [showPreview, setShowPreview] = useState(false);
  const [showDeepAnalysis, setShowDeepAnalysis] = useState(false);
  const [collapsedGroups, setCollapsedGroups] = useState<Record<string, boolean>>({});
  const [crudTab, setCrudTab] = useState<'read' | 'create' | 'update' | 'delete'>('read');
  const [assertionResults, setAssertionResults] = useState<Record<string, 'pass' | 'fail' | 'running' | undefined>>({});
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [scriptSearch, setScriptSearch] = useState('');
  const [showGotchas, setShowGotchas] = useState<Record<string, boolean>>({});
  const [chatLoading, setChatLoading] = useState(false);
  const [chatHistory, setChatHistory] = useState<Array<{
    q: string;
    sql?: string;
    error?: string;
    explanation?: string;
    suggestion?: string;
  }>>([]);

  // P2: Narrative State
  const [generatingReport, setGeneratingReport] = useState(false);
  const [narrativeReport, setNarrativeReport] = useState<string | null>(null);

  // V6.0: Custom Assertions State
  const [customAssertions, setCustomAssertions] = useState<any[]>([]);
  const [customAssertionResults, setCustomAssertionResults] = useState<Record<string, 'pass' | 'fail' | 'running' | undefined>>({});

  useEffect(() => {
    const report = (result as any).narrativeReport || result.semanticSchema?.narrativeReport;
    if (report && !narrativeReport) {
      setNarrativeReport(report);
    }
  }, [result]);

  const handleGenerateReport = async () => {
    setGeneratingReport(true);
    try {
      const report = await aiService.generateNarrativeReport(summary, result, (msg) => {
        // Option: show toast or console or update state
        console.log("Report progress:", msg);
      });
      setNarrativeReport(report);
    } catch (e) {
      console.error(e);
    } finally {
      setGeneratingReport(false);
    }
  };

  const handleExportMarkdown = () => {
    const content = narrativeReport || `# Data Analysis Report: ${summary.tableName}\n\nGenerated by AI Schema...`;
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${summary.tableName}_analysis_report.md`;
    a.click();
  };

  const handleExportData = async (format: 'csv' | 'parquet') => {
    try {
      const buffer = await duckDBService.exportTable(summary.tableName, format);
      const blob = new Blob([buffer as any], { type: format === 'csv' ? 'text/csv' : 'application/octet-stream' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${summary.tableName}.${format}`;
      a.click();
    } catch (e) {
      console.error(e);
      alert("Export failed: " + e);
    }
  };

  // V6.0: Custom Assertion Handlers
  const handleAddCustomAssertion = (assertion: any) => {
    setCustomAssertions(prev => [...prev, assertion]);
  };

  const handleRemoveCustomAssertion = (id: string) => {
    setCustomAssertions(prev => prev.filter(a => a.id !== id));
    setCustomAssertionResults(prev => {
      const newResults = { ...prev };
      delete newResults[id];
      return newResults;
    });
  };

  const handleRunCustomAssertion = async (assertion: any, idx: number) => {
    const key = assertion.id;
    setCustomAssertionResults(prev => ({ ...prev, [key]: 'running' }));
    try {
      const rows = await duckDBService.query(assertion.sql);
      const passed = rows && rows.length > 0 && Object.values(rows[0])[0] === true;
      // For assertions, we check if the result is 0 (no violations = pass)
      const passedCheck = rows && rows.length > 0 ? Object.values(rows[0])[0] === 0 : true;
      setCustomAssertionResults(prev => ({ ...prev, [key]: passedCheck ? 'pass' : 'fail' }));
    } catch {
      setCustomAssertionResults(prev => ({ ...prev, [key]: 'fail' }));
    }
  };

  // v7.0: MECE Operations Data Extraction
  const operationsRaw = result.operations || {};
  const filteredOps = Array.isArray(operationsRaw) ? operationsRaw : (operationsRaw.scripts || []);
  const crudData = Array.isArray(operationsRaw) ? null : operationsRaw.crud;
  const transactionData = Array.isArray(operationsRaw) ? null : operationsRaw.transaction;
  const macrosData: any[] = Array.isArray(operationsRaw) ? [] : (operationsRaw.macros || []);
  const assertionsData: any[] = Array.isArray(operationsRaw) ? [] : (operationsRaw.assertions || []);

  // MECE Script Grouping (6 categories)
  const categorizedGroups = [
    { id: 'schema', title: '鏋舵瀯瀹氫箟 (Schema)', icon: <Database size={14} />, ops: filteredOps.filter((op: any) => op.category === 'schema' || !op.category) },
    { id: 'crud', title: '鍩虹鎿嶄綔 (CRUD)', icon: <Table size={14} />, ops: filteredOps.filter((op: any) => op.category === 'crud') },
    { id: 'analysis', title: '娣卞害鍒嗘瀽 (Analysis)', icon: <Activity size={14} />, ops: filteredOps.filter((op: any) => op.category === 'analysis') },
    { id: 'view', title: '瑙嗗浘绠＄悊 (Views)', icon: <Layers size={14} />, ops: filteredOps.filter((op: any) => op.category === 'view') },
    { id: 'join', title: '澶氳〃鍏宠仈 (Joins)', icon: <Link size={14} />, ops: filteredOps.filter((op: any) => op.category === 'join') },
    { id: 'window', title: '绐楀彛鍑芥暟 (Window)', icon: <BarChart3 size={14} />, ops: filteredOps.filter((op: any) => op.category === 'window') }
  ].filter(g => g.ops.length > 0);

  // Copy to clipboard helper
  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  // Run all assertions batch
  const runAllAssertions = async () => {
    for (let i = 0; i < assertionsData.length; i++) {
      await handleRunAssertion(assertionsData[i], i);
    }
  };

  // Filtered script groups for search
  const filteredScriptGroups = categorizedGroups.map(g => ({
    ...g,
    ops: g.ops.filter((op: any) => {
      if (!scriptSearch.trim()) return true;
      const s = scriptSearch.toLowerCase();
      return (op.title || '').toLowerCase().includes(s) ||
        (op.description || '').toLowerCase().includes(s) ||
        (op.sql || '').toLowerCase().includes(s) ||
        (op.learningNote || '').toLowerCase().includes(s);
    })
  })).filter(g => g.ops.length > 0);


  // Run assertion
  const handleRunAssertion = async (assertion: any, idx: number) => {
    const key = `assertion-${idx}`;
    setAssertionResults(prev => ({ ...prev, [key]: 'running' }));
    try {
      const rows = await duckDBService.query(assertion.sql);
      const passed = rows && rows.length > 0 && Object.values(rows[0])[0] === true;
      setAssertionResults(prev => ({ ...prev, [key]: passed ? 'pass' : 'fail' }));
    } catch {
      setAssertionResults(prev => ({ ...prev, [key]: 'fail' }));
    }
  };

  const toggleGroup = (id: string) => {
    setCollapsedGroups(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const handleExecuteAll = async () => {
    if (!confirm(`确定要执行当前页面的 ${filteredOps.length} 条 SQL 操作吗？这将直接修改数据库。`)) return;

    setExecuting(true);
    const newExecutedOps = { ...executedOps };

    for (const op of filteredOps) {
      try {
        await duckDBService.executeAndAudit(op.sql, 'AI_BATCH_EXEC', summary.tableName, `Batch exec op #${op.id}`);
        newExecutedOps[op.id] = 'success';
      } catch (e) {
        console.error(e);
        newExecutedOps[op.id] = 'error';
      }
      setExecutedOps({ ...newExecutedOps });
    }
    setExecuting(false);
    if (onRefresh) onRefresh();
  };

  // M3: Context Aware Chat
  const handleSend = async (msgOverride?: string) => {
    const question = msgOverride || chatInput;
    if (chatLoading || !question.trim()) return;

    setChatLoading(true);
    setChatInput('');

    // Add User Message
    setChatHistory(prev => [...prev, { q: question }]);

    try {
      // 1. Prepare Rich Context
      const context = {
        tableName: summary.tableName,
        semanticColumns: result.semanticColumns,
        metrics: result.metricScorecards,
        featureProposals: result.featureProposals,
        stats: summary.stats
      };

      // 2. Generate SQL, Explanation & Suggestion in ONE call
      const response = await aiService.unifiedChat(question, context);

      setChatHistory(prev => prev.map(m => m.q === question ? {
        ...m,
        sql: response.sql,
        explanation: response.explanation,
        suggestion: response.suggestion
      } : m));

    } catch (e: any) {
      setChatHistory(prev => prev.map(m => m.q === question ? { ...m, error: e.message } : m));
    } finally {
      setChatLoading(false);
    }
  };

  const handlePreview = async (sql: string, opId: number) => {
    // Toggle off if clicking same
    if (activePreviewId === opId) {
      setActivePreviewId(null);
      setPreviewData(null);
      return;
    }

    setActivePreviewId(opId);
    setPreviewData(null);
    setPreviewError(null);

    try {
      const data = await duckDBService.previewSql(sql);
      setPreviewData(data);
    } catch (e: any) {
      setPreviewError(e.message);
    }
  };

  const handleDownloadReport = () => {
    // v4.0 Enhanced Report
    const lines = [
      `# Data Analysis Report: ${fileName}`,
      `Generated by AI Schema Agent v4.0 at ${new Date().toLocaleString()}`,
      ``,
      `## 📊 Executive Summary`,
      `- **Table**: ${summary.tableName}`,
      `- **Rows**: ${summary.rowCount.toLocaleString()}`,
      `- **Columns**: ${summary.columnCount}`,
      `- **Quality Grade**: ${result.qualityReport?.overallScore ? (result.qualityReport.overallScore >= 90 ? 'A (Excellent)' : 'B/C/D') + ` (${result.qualityReport.overallScore}/100)` : 'N/A'}`,
      `- **Overview**: ${result.overview}`,
      ``,
      `## 🛡️ Quality Audit`,
      `${(result.qualityReport?.issues || []).map((i: any) => `- [${i.severity.toUpperCase()}] ${i.type} on ${i.column}: ${i.detail}`).join('\n') || 'No major issues found.'}`,
      ``,
      `## 🧩 Semantic Schema`,
      `| Column | Type | Semantic | Confidence | Description |`,
      `|---|---|---|---|---|`,
      ...(result.semanticColumns || []).map((c: any) => `| ${c.name} | ${c.physicalType} | ${c.semanticType} | ${(c.confidence * 100).toFixed(0)}% | ${c.description || ''} |`),
      ``,
      `## 🛠️ Operational Plan`,
    ];

    // Use filteredOps which acts as the centralized array of script objects
    filteredOps.forEach((op: any) => {
      const status = executedOps[op.id] === 'success' ? '鉁?Executed' : executedOps[op.id] === 'error' ? '鉂?Failed' : '猬?Pending';
      lines.push(`#### ${op.id}. ${op.title} (${status})`);
      lines.push(`> ${op.interpretation}`);
      lines.push('```sql');
      lines.push(op.sql);
      lines.push('```');
      lines.push('');
    });

    // Include Insights if available
    if (result.metricScorecards?.length > 0) {
      lines.push(`## 📋搱 Key Metrics`);
      result.metricScorecards.forEach((m: any) => {
        lines.push(`- **${m.displayName}**: Total=${m.total}, Avg=${m.mean?.toFixed(2)}`);
      });
      lines.push('');
    }

    if (chatHistory.length > 0) {
      lines.push(`## 📋挰 Exploration History`);
      chatHistory.forEach((msg, i) => {
        lines.push(`**Q${i + 1}: ${msg.q}**`);
        if (msg.sql) {
          lines.push('```sql');
          lines.push(msg.sql);
          lines.push('```');
        }
        if (msg.error) lines.push(`> Error: ${msg.error}`);
        lines.push('');
      });
    }

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Analysis_${summary.tableName}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-6xl mx-auto mt-12 space-y-8">
      {/* V6.0: Core Hero Card - Three-Tier Architecture Layer 1 */}
      <CoreHeroCard
        tableName={summary.tableName}
        rowCount={summary.rowCount}
        columnCount={summary.columnCount}
        qualityScore={result.qualityReport?.overallScore}
        overview={result.overview}
        userIntent={result.userIntent}
      />

      {/* Three-Column Layout Container */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Quick Stats & Quality */}
        <div className="lg:col-span-3 space-y-6">
          {/* Quality Badge */}
          <QualityBadge report={result.qualityReport || null} />
          
          {/* Key Metrics Quick View */}
          {(result.keyMetrics && result.keyMetrics.length > 0) && (
            <div className="bg-white rounded-xl border border-gray-200 p-4">
              <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                <BarChart3 size={14} className="text-blue-500" /> 关键指标
              </h4>
              <div className="space-y-2">
                {result.keyMetrics.slice(0, 3).map((metric: any, i: number) => (
                  <div key={i} className="flex items-center justify-between p-2 bg-gray-50 rounded-lg">
                    <div>
                      <div className="text-xs font-bold text-gray-800 truncate">{metric.name}</div>
                      <div className="text-[10px] text-gray-500">{metric.unit || ''}</div>
                    </div>
                    <ConfidenceBadge 
                      score={metric.confidenceScore} 
                      showScore={true} 
                      size="sm" 
                    />
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Handbook CTA */}
          <div 
            className="bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl p-4 text-white shadow-lg cursor-pointer hover:scale-[1.02] transition-transform"
            onClick={onGenerateHandbook}
          >
            <div className="flex items-center gap-2 mb-2">
              <BookOpen size={16} />
              <span className="text-sm font-bold">生成完整手册</span>
            </div>
            <p className="text-[10px] text-white/80">
              基于 {summary.columnCount} 鍒?/ {summary.rowCount} 琛?            </p>
          </div>
        </div>

        {/* Center Column: Main Content */}
        <div className="lg:col-span-6 space-y-6">
          {/* Semantic Dictionary - Collapsed by default for large tables */}
          <SectionCard
            title="语义字典"
            icon={<Layers size={16} />}
            badge={result.semanticColumns?.length}
            badgeColor="#3B82F6"
            defaultExpanded={true}
          >
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-gray-50 text-gray-500 font-bold uppercase text-[10px] tracking-wider">
                  <tr>
                    <th className="px-3 py-2 text-left">列名</th>
                    <th className="px-3 py-2 text-left">语义类型</th>
                    <th className="px-3 py-2 text-center">置信度</th>
                    <th className="px-3 py-2 text-left">说明</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {(result.semanticColumns || []).slice(0, 10).map((col: any, i: number) => (
                    <tr key={i} className="hover:bg-blue-50/30 transition-colors group">
                      <td className="px-3 py-2 font-mono font-bold text-gray-900 text-xs">{col.name}</td>
                      <td className="px-3 py-2">
                        <span 
                          className="px-2 py-0.5 rounded-lg text-[10px] font-black"
                          style={{ 
                            backgroundColor: `${getSemanticTypeColor(col.semanticType)}15`,
                            color: getSemanticTypeColor(col.semanticType),
                          }}
                        >
                          {col.semanticType}
                        </span>
                      </td>
                      <td className="px-3 py-2">
                        <ConfidenceBar 
                          score={col.confidenceScore || Math.round(col.confidence * 100)} 
                          showLabel={false}
                          height={4}
                        />
                      </td>
                      <td className="px-3 py-2 text-gray-500 text-xs italic">
                        {col.description || '--'}
                        {/* Show reasoning if available */}
                        {col.reasoning && (
                          <ReasoningToggle 
                            reasoning={col.reasoning} 
                            label="查看推理" 
                          />
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              {result.semanticColumns && result.semanticColumns.length > 10 && (
                <div className="text-center py-2 text-xs text-gray-400">
                  还有 {result.semanticColumns.length - 10} 列....
                </div>
              )}
            </div>
          </SectionCard>

          {/* Quality Issues */}
          {result.qualityReport && result.qualityReport.issues.length > 0 && (
            <SectionCard
              title="质量问题"
              icon={<Shield size={16} />}
              badge={result.qualityReport.issues.length}
              badgeColor={getQualityColor(result.qualityReport.overallScore)}
              defaultExpanded={true}
            >
              <div className="space-y-2">
                {result.qualityReport.issues.slice(0, 5).map((issue: any, i: number) => (
                  <div 
                    key={i} 
                    className={`p-3 rounded-lg border-l-3 ${
                      issue.severity === 'error' ? 'bg-red-50 border-red-500' :
                      issue.severity === 'warning' ? 'bg-amber-50 border-amber-500' :
                      'bg-blue-50 border-blue-500'
                    }`}
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-bold text-gray-900 text-xs">[{issue.column}] {issue.type}</span>
                      <span className={`text-[9px] px-1.5 rounded uppercase font-bold ${
                        issue.severity === 'error' ? 'text-red-700 bg-red-200' :
                        issue.severity === 'warning' ? 'text-amber-700 bg-amber-200' :
                        'text-blue-700 bg-blue-200'
                      }`}>{issue.severity}</span>
                    </div>
                    <p className="text-gray-600 text-xs">{issue.detail}</p>
                    <p className="text-gray-800 text-xs font-medium mt-1">鈫?{issue.suggestion}</p>
                  </div>
                ))}
              </div>
              {result.qualityReport.reasoning && (
                <ReasoningToggle 
                  reasoning={result.qualityReport.reasoning}
                  label="查看评分推理"
                />
              )}
            </SectionCard>
          )}

          {/* Key Metrics Detail */}
          <SectionCard
            title="关键指标"
            icon={<BarChart3 size={16} />}
            badge={result.keyMetrics?.length}
            badgeColor="#10B981"
            defaultExpanded={true}
          >
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {result.keyMetrics?.map((metric: any, i: number) => (
                <div key={i} className="bg-gray-50 rounded-lg p-4 border border-gray-100">
                  <div className="flex items-center justify-between mb-2">
                    <h6 className="font-bold text-gray-800 text-sm">{metric.name}</h6>
                    <ConfidenceBadge score={metric.confidenceScore} size="sm" />
                  </div>
                  {metric.formula && (
                    <div className="bg-slate-900 rounded p-2 font-mono text-[10px] text-emerald-400 mb-2 overflow-x-auto">
                      {metric.formula}
                    </div>
                  )}
                  <p className="text-xs text-gray-600">{metric.explanation}</p>
                  {/* Show assumptions if available */}
                  <AssumptionBadge 
                    assumption={metric.assumption}
                    limitation={metric.limitation}
                    confidence={metric.confidenceScore}
                  />
                </div>
              ))}
            </div>
          </SectionCard>
        </div>

        {/* Right Column: SQL Operations */}
        <div className="lg:col-span-3 space-y-6">
          {/* SQL Scripts Quick Access */}
          {filteredOps.length > 0 && (
            <div className="bg-white rounded-xl border border-gray-200 p-4">
              <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                <Terminal size={14} className="text-slate-500" /> SQL 脚本
              </h4>
              <div className="space-y-2">
                {filteredOps.slice(0, 5).map((op: any) => (
                  <button
                    key={op.id}
                    onClick={() => onExecuteSql(op.sql)}
                    className="w-full flex items-center justify-between p-2 bg-gray-50 hover:bg-gray-100 rounded-lg text-left transition-colors"
                  >
                    <span className="text-xs font-medium text-gray-700 truncate flex-1">{op.title || op.name}</span>
                    <Play size={10} className="text-blue-500" />
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Assertions Summary */}
          {(assertionsData.length > 0 || customAssertions.length > 0) && (
            <div className="bg-white rounded-xl border border-gray-200 p-4">
              <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                <TestTube2 size={14} className="text-rose-500" /> 断言验证
              </h4>
              <div className="space-y-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="text-gray-600">AI 生成</span>
                  <span className="font-bold text-gray-900">{assertionsData.length}</span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-gray-600">自定义</span>
                  <span className="font-bold text-gray-900">{customAssertions.length}</span>
                </div>
                {Object.keys(assertionResults).length > 0 && (
                  <div className="pt-2 border-t border-gray-100">
                    <div className="flex items-center gap-2 text-[10px]">
                      <span className="text-green-600 font-bold">
                        {Object.values(assertionResults).filter(v => v === 'pass').length} 通过
                      </span>
                      <span className="text-gray-300">/</span>
                      <span className="text-red-600 font-bold">
                        {Object.values(assertionResults).filter(v => v === 'fail').length} 失败
                      </span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* SQL Engineering Center - Full Width Below */}
      {
        (filteredOps.length > 0 || crudData || macrosData.length > 0 || assertionsData.length > 0) && (
          <section className="relative bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 rounded-2xl p-0.5 text-white shadow-2xl overflow-hidden mb-8 border border-slate-700/50">
            {/* ... (keeping the existing SQL Engineering Center code) */}
            <div className="relative bg-slate-900/80 backdrop-blur-xl rounded-t-[calc(1rem-1px)] px-8 py-6 border-b border-slate-700/50">
              <div className="flex justify-between items-center">
                <div>
                  <div className="inline-flex items-center gap-2 px-3 py-1 bg-amber-500/10 text-amber-400 rounded-full text-[10px] font-bold mb-2 border border-amber-500/20">
                    <Terminal size={10} /> Stage 3/6 | SQL 工程 | {filteredOps.length} Scripts
                  </div>
                  <h4 className="text-xl font-bold text-white flex items-center gap-3">
                    <div className="p-2 bg-blue-500/10 rounded-lg border border-blue-500/20">
                      <Wrench size={20} className="text-blue-400" />
                    </div>
                    SQL 工程中心 (Operations)
                  </h4>
                </div>

                {/* Batch Execute Button */}
                {filteredOps.length > 0 && (
                  <button
                    onClick={handleExecuteAll}
                    disabled={executing}
                    className={`flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-xs transition-all ${executing
                      ? 'bg-slate-700 text-slate-400 cursor-not-allowed'
                      : 'bg-gradient-to-r from-green-500 to-emerald-600 text-white hover:from-green-400 hover:to-emerald-500 shadow-lg shadow-green-500/20 transform hover:-translate-y-0.5'
                      }`}
                  >
                    {executing ? (
                      <><div className="w-3 h-3 border-2 border-slate-500 border-t-slate-300 rounded-full animate-spin" /> 执行中...</>
                    ) : (
                      <><Zap size={14} /> 全部执行 ({filteredOps.length})</>
                    )}
                  </button>
                )}
              </div>
            </div>

            <div className="relative bg-slate-900/60 backdrop-blur-xl rounded-b-[calc(1rem-1px)] p-6 space-y-6">
              {/* ... (keeping existing CRUD and script sections) */}
              
              {/* V6.0: Custom Assertion Panel Integration */}
              {customAssertions.length > 0 && (
                <div className="mt-6">
                  <CustomAssertionPanel
                    tableName={summary.tableName}
                    columns={(result.semanticColumns || []).map((c: any) => c.name)}
                    customAssertions={customAssertions}
                    onAddAssertion={handleAddCustomAssertion}
                    onRemoveAssertion={handleRemoveCustomAssertion}
                    onRunAssertion={handleRunCustomAssertion}
                    assertionResults={customAssertionResults}
                  />
                </div>
              )}
            </div>
          </section>
        )
      }

      {/* ... (keeping the rest of the component) */}
    </div>
  );
};

export default ResultCard;

