const fs = require('fs');
const path = require('path');

const content = `export interface WikiNodeRaw {
  id: string;
  categoryId: string;
  categoryTitle: string;
  title: string;
  iconName: string;
  brief: string;
  seedIds: string[];
  coreNodes: string[];
  nodeCount: number;        // 预设实体节点数
  linkCount: number;        // 预设关系连线数
  coreConcept?: string;     // 核心学术/工程概念
  mindAction: string;       // 本课训练的核心心智动作
  graphFocus: string;       // 图谱注入后重点观察的视觉结构特征
  caseBackground: string;   // 源教程文本材料的大白话案例背景说明
  description: string;
  stageId: 'phase1' | 'phase2' | 'phase3' | 'phase4';
  stageTitle: string;
  lessonNum: string;
}

export const ONTOLOGY_STAGES = [
  { id: 'phase1', title: '阶段一：识别与边界', badge: '识别与边界', desc: '区分事实与推断，识别具备唯一身份的对象与动态过程' },
  { id: 'phase2', title: '阶段二：拓扑与变迁', badge: '拓扑与变迁', desc: '将对象连接到过程，命名角色、记录状态变迁与有向关系' },
  { id: 'phase3', title: '阶段三：组装与验证', badge: '组装与验证', desc: '组装无冗余的最小模型，用反向提问与迁移测试校验模型自洽' },
  { id: 'phase4', title: '阶段四：演进与证据', badge: '演进与证据', desc: '平滑扩展增量材料，用双信源解耦冲突，让关键结论回归证据' },
] as const;

export const DEFAULT_PATTERNS: WikiNodeRaw[] = [
  // ── 阶段一：识别与边界 ──────────────────────────────────────────
  {
    id: 'lesson-0001',
    lessonNum: '0001',
    stageId: 'phase1',
    stageTitle: '阶段一：识别与边界',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 01 课：只写材料真正告诉你的事',
    iconName: 'BookOpen',
    nodeCount: 7,
    linkCount: 6,
    coreConcept: 'Fact vs Inference vs Unknown',
    brief: '建模的第一步：严格区分“事实、推断与未知”，只记录确凿依据。',
    mindAction: '严格只画原文直接证明的线索，绝不凭常识脑补未知信息',
    graphFocus: '观察自左至右的单向流：做菜/买菜事实向就餐汇聚，并明确剥离出不可脑补的“未知·第三人”盲区',
    seedIds: ['lesson-0001'],
    coreNodes: ['做菜人·妈妈', '买菜人·我', '自做茄子', '三人用餐', '推断·菜已带回', '未知·第三人'],
    caseBackground: '中午，妈妈在家做了一道茄子。我去餐馆买了两道菜，回家后，我们三个人一起吃饭。',
    description: '训练“不脑补”的建模习惯。事实是原文直接说明的内容，推断是有线索但未确证的假设。',
  },
  {
    id: 'lesson-0002',
    lessonNum: '0002',
    stageId: 'phase1',
    stageTitle: '阶段一：识别与边界',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 02 课：找出需要保持身份的对象',
    iconName: 'Sparkles',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Entity Identity & Instance Tracking',
    brief: '识别具备独立、连续唯一身份的实体（人物、设备、资产等）。',
    mindAction: '问自己：这个东西是否有连续独立的唯一 Identity 业务主键？',
    graphFocus: '观察左侧人员与仓库实体汇聚于中心的“包裹交接”事件，向右派生物资标的与数字签收凭据',
    seedIds: ['lesson-0002'],
    coreNodes: ['仓管·周姐', '配送·小林', '1号仓库', '包裹交接', '包裹B', '签收凭单'],
    caseBackground: '上午，小林进入仓库1。管理员周姐把包裹B交给小林。随后，小林离开仓库。',
    description: '区分独立对象与普通数值属性。只有需要被持续跟踪身份的才是对象 (Object)。',
  },
  {
    id: 'lesson-0003',
    lessonNum: '0003',
    stageId: 'phase1',
    stageTitle: '阶段一：识别与边界',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 03 课：找出发生了什么过程',
    iconName: 'Activity',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Process Object & State Machine',
    brief: '过程 (Process) 是有时间起止的动态事件，负责连接多个对象。',
    mindAction: '寻找带时间边界与状态变化的动态“动作事件”',
    graphFocus: '观察居于核心枢纽的主采购流程如何向右分解出比价与验收子阶段，最终锁定供应商与算力服务器',
    seedIds: ['lesson-0003'],
    coreNodes: ['采购员·李四', '服务器采购', '比价决策', '联众科技', '到货验收', '算力服务器'],
    caseBackground: '采购员李四在周一发起服务器设备采购流程，经历供应商比价与物资入库验收。',
    description: '对象是静态的，过程是动态的。过程记录了“在特定时刻发生了什么”。',
  },

  // ── 阶段二：拓扑与变迁 ──────────────────────────────────────────
  {
    id: 'lesson-0004',
    lessonNum: '0004',
    stageId: 'phase2',
    stageTitle: '阶段二：拓扑与变迁',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 04 课：把对象连接到过程',
    iconName: 'GitBranch',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Topology & Role Semantic',
    brief: '一次只看一个过程，把材料明确涉及的对象连结到该过程。',
    mindAction: '圈出单个过程，问“这件事明确涉及哪些已有主体与客体？”',
    graphFocus: '观察左侧合规与法务人员连同协议标的共同汇聚至中心审批流，并向右归档至存证单与合规审计库',
    seedIds: ['lesson-0004'],
    coreNodes: ['合规专家·王五', '法务初审·小刘', '年度框架协议', '框架协议审批', '生效存证单', '合规审计库'],
    caseBackground: '合规专家王五接入采购框架协议审批流，审查并签署了《年度采购框架协议.pdf》。',
    description: '将孤立的对象与过程打通，形成第一张初具形态的关联拓扑。',
  },
  {
    id: 'lesson-0005',
    lessonNum: '0005',
    stageId: 'phase2',
    stageTitle: '阶段二：拓扑与变迁',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 05 课：为过程中的角色命名',
    iconName: 'Layers',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Link Role Qualification',
    brief: '在连接线上明确标出对象在过程中扮演的“业务角色”。',
    mindAction: '不只连线，必须在关系线上写清“买方/卖方/担保方”',
    graphFocus: '注意三方主体（买方/卖方/监管方）到交易中枢的有向连线上的语义角色，向右分流至实物车与资金账户',
    seedIds: ['lesson-0005'],
    coreNodes: ['买方·小张', '卖方·老李', '资金托管方', '车辆转让交易', '车辆·Model3', '资金托管账户'],
    caseBackground: '买方小张与卖方老李在二手车交易平台上达成协议，通过资金托管中间方进行车辆权属转让。',
    description: '同样的实体在不同过程中扮演不同角色，角色赋予关系具体的业务含义。',
  },
  {
    id: 'lesson-0006',
    lessonNum: '0006',
    stageId: 'phase2',
    stageTitle: '阶段二：拓扑与变迁',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 06 课：记录状态的改变',
    iconName: 'Clock',
    nodeCount: 6,
    linkCount: 6,
    coreConcept: 'State Transition & Event Writeback',
    brief: '过程发生后，对象的状态会发生改变，需要显式建模。',
    mindAction: '跟踪过程前后对象的“初始状态 ➔ 目标状态”转移',
    graphFocus: '横向树下清晰呈现“订单与待支付状态 ➔ 扫码支付触发事件 ➔ 已支付状态与银行对账单”的清晰单向演进',
    seedIds: ['lesson-0006'],
    coreNodes: ['顾客·王女士', '订单·2026', '待支付状态', '扫码支付', '已支付状态', '银行对账单'],
    caseBackground: '顾客针对订单 ORD-2026 完成了微信扫码支付，触发支付成功事件，订单状态跃迁为已支付待履约。',
    description: '业务状态不是孤立存在，它是由特定过程触发并附着在对象身上的。',
  },
  {
    id: 'lesson-0007',
    lessonNum: '0007',
    stageId: 'phase2',
    stageTitle: '阶段二：拓扑与变迁',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 07 课：写出对象之间的直接关系',
    iconName: 'BookMarked',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Bi-directional Link Traversal',
    brief: '表达不依赖特定过程的静态结构关系，并严格注意有向性。',
    mindAction: '严格校验关系的单向读法（如：部门管辖项目，员工隶属部门）',
    graphFocus: '观察组织人员、研发部门、重构工程到技术基座与标准的清晰三层静态结构继承脉络',
    seedIds: ['lesson-0007'],
    coreNodes: ['架构总监·孙老师', '前端·小赵', '架构研发部', '内核重构项目', '图引擎核心库', '工程发布规范'],
    caseBackground: '前端工程师小赵隶属于 UI/UX 架构研发部，负责推进 Ontology 内核重构项目，形成清晰拓扑结构。',
    description: '对象之间的直接关系（如归属、包含）具备方向性，不可混淆主客体。',
  },

  // ── 阶段三：组装与验证 ──────────────────────────────────────────
  {
    id: 'lesson-0008',
    lessonNum: '0008',
    stageId: 'phase3',
    stageTitle: '阶段三：组装与验证',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 08 课：组装一个最小本体模型',
    iconName: 'Zap',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Minimal Viable Enterprise Ontology (MVO)',
    brief: '合并已验证的对象、过程、角色、状态和关系，消除冗余。',
    mindAction: '将所有构件无重复合并，获得第一张完整最小拓扑图',
    graphFocus: '体验从客户与商品下单、出库就绪、特快运单到终端签收闭环的完整 5 列 MVO 流畅展开',
    seedIds: ['lesson-0008'],
    coreNodes: ['客户·Alice', '工学椅·ErgoX', '商城下单', '待出库状态', '顺丰运单', '客户已签收'],
    caseBackground: 'VIP 客户 Alice 在商城下单购买人体工学椅 ErgoX，系统派发顺丰特快运单 SF-9920 进行物流履约，形成闭环。',
    description: '不发明新概念，只将前面学到的 5 类构件紧凑无瑕地整合为一个自洽视图。',
  },
  {
    id: 'lesson-0009',
    lessonNum: '0009',
    stageId: 'phase3',
    stageTitle: '阶段三：组装与验证',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 09 课：用问题检验模型',
    iconName: 'HelpCircle',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Introspection Probe & Lineage Completeness',
    brief: '提出业务反向问题，检验模型是否存在遗漏、混淆或过度推断。',
    mindAction: '用“谁在何时做了什么系统修改”反向在图谱路径中寻找探针答案',
    graphFocus: '尝试沿着反思探针链路（SRE认领 ➔ 告警 ➔ 内存调整 ➔ DuckDB实例 ➔ 内存32GB与审计留痕）验证全血缘闭环',
    seedIds: ['lesson-0009'],
    coreNodes: ['SRE·张博', '高负载告警', '内存上限调整', 'DuckDB实例', '内存32GB状态', '审计留痕日志'],
    caseBackground: '凌晨 02:15，SRE 运维工程师张博执行生产 DB 内存上限调整事件，将 DuckDB 的 max_memory 从 16GB 调整为 32GB。',
    description: '模型好不好，拿真实业务问题来查。查不出来说明缺少构件，查出多个答案说明混淆。',
  },
  {
    id: 'lesson-0010',
    lessonNum: '0010',
    stageId: 'phase3',
    stageTitle: '阶段三：组装与验证',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 10 课：把模型用到新案例',
    iconName: 'CheckCircle',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Object Interface & Polymorphic Pattern',
    brief: '将已建立的模式迁移应用到全新的业务场景中。',
    mindAction: '判断新场景是复用现有模式、微调扩展还是超出范围',
    graphFocus: '观察通过“算力标准接口”多态抽象，上层集群订阅与底层物理 GPU 节点解耦的优雅层次结构',
    seedIds: ['lesson-0010'],
    coreNodes: ['客户·独角兽B', '商务·周敏', '算力集群订阅', '算力标准接口', 'GPU节点04', '就绪接入状态'],
    caseBackground: 'AI 独角兽企业客户 B 采购了 H100 云算力集群月度订阅，平台为其自动绑定并分配了 GPU 计算节点 Cluster#04。',
    description: '检验本体能力的金标准：脱离原案例，在新业务场景中能否快速套用与微调。',
  },
  {
    id: 'lesson-0011',
    lessonNum: '0011',
    stageId: 'phase3',
    stageTitle: '阶段三：组装与验证',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 11 课：独立完成可验证模型',
    iconName: 'CheckCircle',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Auditable Credit Decisioning',
    brief: '零提示独立完成具备自洽逻辑与多视角验证的图谱模型。',
    mindAction: '从头独立拆解材料、建图并完成风控授信闭环',
    graphFocus: '检查 [借款人] ➔ [申请单] ➔ [风控审批流] ➔ [评分卡] ➔ [授信账户] ➔ [激活状态] 的完整可解释决策拓扑',
    seedIds: ['lesson-0011'],
    coreNodes: ['借款人·赵六', '贷款申请单', '风控审批流', '评分卡·720', '消费授信账户', '授信可用状态'],
    caseBackground: '借款人赵六提交个人消费贷款申请，智能风控审批流 V4.2 自动运行信用分评估，为赵六开设 ￥50,000 消费授信账户。',
    description: '独立手操测试！构建完整的金融贷款申请与自动化风控闭环拓扑。',
  },

  // ── 阶段四：演进与证据 ──────────────────────────────────────────
  {
    id: 'lesson-0012',
    lessonNum: '0012',
    stageId: 'phase4',
    stageTitle: '阶段四：演进与证据',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 12 课：用新事实更新模型',
    iconName: 'Sparkles',
    nodeCount: 6,
    linkCount: 5,
    coreConcept: 'Incremental Fact & Dynamic Risk Evolution',
    brief: '面对业务增量事实，在不推翻原模型的前提下平滑扩充节点。',
    mindAction: '将新增事实作为增量子图挂载在已有账户主线上',
    graphFocus: '看存量账户如何在保持正常交易主线的同时，平滑分支挂载突发异地登录事实与高危主动防御子图',
    seedIds: ['lesson-0012'],
    coreNodes: ['账户·C-901', '正常交易流', '异地登录事件', '反欺诈引擎', '高危防盗标记', '强制人脸验证'],
    caseBackground: '客户账户 C-901 突发境外异地登录事件，反欺诈风控引擎实时捕获增量事实，平滑挂载 Level3 高危防盗标记。',
    description: '本体模型具备演进性 (Evolutionary)。新需求来了挂载子图，绝不推翻重做。',
  },
  {
    id: 'lesson-0013',
    lessonNum: '0013',
    stageId: 'phase4',
    stageTitle: '阶段四：演进与证据',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 13 课：处理相互冲突的材料',
    iconName: 'AlertTriangle',
    nodeCount: 7,
    linkCount: 7,
    coreConcept: 'Conflict Resolution & Weight Arbitration',
    brief: '建模多来源矛盾事实，通过信源 (Source) 与置信度解耦。',
    mindAction: '绝不强行抹平矛盾，保留双信源节点并标注置信度与事实差异',
    graphFocus: '观察对称的双信源钻石拓扑：供应商同时接入企业自报与司法公开，冲突事实由风控仲裁器加权决策',
    seedIds: ['lesson-0013'],
    coreNodes: ['供应商·X科技', '信源·企业自报', '信源·司法公开', '声明·利润增20%', '涉诉·被执行1500万', '风控仲裁引擎', '暂缓准入结论'],
    caseBackground: '供应商 X 科技公司在自报财报中声称净利润增长 20%，但第三方数据源接入法院公开执行公告，显示其存在被执行案款 ￥1,500 万。',
    description: '当不同来源说法相反时，不要强行二选一，用双信源节点记录冲突事实。',
  },
  {
    id: 'lesson-0014',
    lessonNum: '0014',
    stageId: 'phase4',
    stageTitle: '阶段四：演进与证据',
    categoryId: 'ontology-course',
    categoryTitle: '本体建模基础实战教程',
    title: '第 14 课：让模型结论回到证据',
    iconName: 'FileCheck',
    nodeCount: 7,
    linkCount: 7,
    coreConcept: 'Claims to Evidence Lineage',
    brief: '为关键结论绑定当前有效的原文证据，让模型具备可解释与追溯性。',
    mindAction: '为每条交付结论挂载原文依据，并标记有效/待确认状态',
    graphFocus: '看交付合格出厂结论如何严密回溯至王工检测结论与复核单，并直观见证主管更正单对错误初检的纠偏废止',
    seedIds: ['lesson-0014'],
    coreNodes: ['样品·S', '初检记录·作废', '主管更正单', '复核单·合格', '结论·检测人王工', '交付·合格出厂'],
    caseBackground: '原记录：陈工在实验室1检测样品S。主管更正单：实际检测人是王工，陈工为录入错误。确认记录：刘工在实验室1复核样品S，复核后标记为合格。未确认消息：复核地点可能是实验室2；结果可能是不合格。',
    description: '图谱结论不能悬空。每条交付结论必须回到当前有效的原文证据。',
  }
];
`;

const targetFile = path.resolve(__dirname, '../components/Library/defaultPatterns.ts');
fs.writeFileSync(targetFile, content, 'utf8');
console.log('Successfully updated:', targetFile);
